package com.example.graphql;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Table;

/**
 * Domain model for an Item entity.
 *
 * <p>Represents an item with a unique ID, name, and description. Used in the
 * GraphQL API and persisted in the database. Implemented as a sealed record
 * with Jakarta Bean Validation annotations.</p>
 *
 * @param id unique identifier (auto-generated by database)
 * @param name item name (required, non-blank, 1-255 characters)
 * @param description item description (optional, max 2000 characters)
 */
@Table("items")
public record Item(
        @Id
        String id,
        @NotBlank(message = "Item name is required and cannot be blank")
        @Size(min = 1, max = 255, message = "Item name must be between 1 and 255 characters")
        String name,
        @Size(max = 2000, message = "Item description must not exceed 2000 characters")
        String description
) {
    /**
     * Compact constructor for validation.
     */
    public Item {
        // Validation is handled by Jakarta Bean Validation annotations
    }
}
