package com.example.graphql;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Table;

/**
 * Domain model for a hierarchical Item entity.
 *
 * <p>Represents an item with unique ID, name, description, and optional parent reference.
 * Supports hierarchical organization where items can have child items.
 * Implemented as a sealed record with Jakarta Bean Validation annotations.</p>
 *
 * @param id unique identifier (auto-generated by database)
 * @param name item name (required, non-blank, 1-255 characters)
 * @param description item description (optional, max 2000 characters)
 * @param parentId optional parent item ID for hierarchical relationships
 */
@Table("items")
public record Item(
        @Id
        String id,
        @NotBlank(message = "Item name is required and cannot be blank")
        @Size(min = 1, max = 255, message = "Item name must be between 1 and 255 characters")
        String name,
        @Size(max = 2000, message = "Item description must not exceed 2000 characters")
        String description,
        String parentId
) {
    /**
     * Compact constructor for validation.
     */
    public Item {
        // Validation is handled by Jakarta Bean Validation annotations
    }

    /**
     * Constructor for creating root items (no parent).
     *
     * @param id unique identifier
     * @param name item name
     * @param description item description
     */
    public Item(String id, String name, String description) {
        this(id, name, description, null);
    }
}
