
package com.example.graphql;

import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Table;

/**
 * Domain model for an Item entity.
 *
 * <p>Represents an item with a unique ID, name, and description. Used in the
 * GraphQL API and persisted in the database.</p>
 *
 * @param id unique identifier (generated by DB)
 * @param name item name
 * @param description item description
 */
@Table("items")
public record Item(@Id String id, String name, String description) {}
